version: '3.2'
 
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_ROOT_DATABASE: tech-challenge-product
    networks:
      - ambiente
  app:
    restart: always
    container_name: App
    build:
      context: .
    ports:
      - "8000:8000"
      - "8085:8082"
    environment:
      MONGO_HOST: mongodb
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    depends_on:
      - mongodb
    links:
      - mongodb
    networks:
      - ambiente
networks: 
  ambiente:
    driver: bridge
