server:
  port: 8082
spring:
  application:
    name: tech-challenge-product
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port:
      database: tech-challenge-product
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

