apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      name: http
      port: 8082
      targetPort: 8082
      nodePort: 30003