apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-product
  labels:
    app: tech-challenge-product
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-product
  template:
    metadata:
      labels:
        app: tech-challenge-product
    spec:
      containers:
      - name: tech-challenge-product
        image: daniel36/tech-challenge-product:1
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 0.2
            memory: "512Mi"
        env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mongo-host
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mongo-port
        - name: MONGO_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongo-config-map
              key: mysql-database-name
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
     
---
apiVersion: v1
kind: Service
metadata:
  name: app-tech-challenge
  labels:
    app: app-tech-challenge
spec:
  type: LoadBalancer
  selector:
    app: app-tech-challenge
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002