apiVersion: "v1"
kind: "Service"
metadata:
  name: "mongo-db"
  labels:
    app: "mongo-db"
spec:
  externalTrafficPolicy: "Local"
  ports:
    - name: "mongodb"
      port: 27017
      nodePort: 30332
  type: "LoadBalancer"
  selector:
    app: "mongo-db"