name: Deploy
on:
  workflow_call:
jobs:
  Develop:
    runs-on: ubuntu-latest
    steps:
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - run: aws sts get-caller-identity

    - run: aws eks update-kubeconfig --region us-east-1 --name dev

    - run: kubectl get svc

    - run: kubectl apply -f k8s/products-deployment.yaml
    - run: kubectl apply -f k8s/products-service.yaml
    - run: kubectl apply -f k8s/products-hpa.yaml
